language: java
jdk:
- oraclejdk7
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn covertura:cobertura
after_success:
  - mvn clean cobertura:cobertura coveralls:report
