before_install: cd team_four
language: java
sudo: false
jdk:
- oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=false -B -V
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)