sudo: false # faster builds
before_install: cd team_four
 - jdk_switcher use oraclejdk8
language: java
jdk:
- oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=false -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash)