language: java
env:
  global:
    - COVERALLS_REPO_TOKEN=hoeYAVnEM07Y2R3VYLyqXWjSy5D77D8Zu
    - CI_NAME=travis-ci
branches:
    only:
        - master
        - development
after_success:
- ./gradlew jacocoTestReport coveralls
