language: java
jdk:
  - oraclejdk9
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
  - mvn covertura:cobertura
after_success:
  - mvn clean cobertura:cobertura coveralls:report
