language: java
jdk:
- oraclejdk7
install:
  - ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=false -B -V
script:
  - mvn covertura:cobertura
after_success:
  - mvn clean cobertura:cobertura coveralls:report
